"""
Safety Agent.

Responsible for validating requests and responses.

Future enhancements:
- Azure AI Content Safety API
- Risk classification
- Policy enforcement
"""

from src.agents.base import BaseAgent
from src.config import get_logger

logger = get_logger(__name__)


class SafetyAgent(BaseAgent):
    """
    Safety validation agent.

    Responsibilities:
    - Review generated answers
    - Identify unsafe responses
    - Approve or reject content
    """

    def __init__(self):

        super().__init__(
            name="SafetyAgent",
            prompt_file="safety.txt",
        )

    def review(
        self,
        content: str,
    ) -> str:
        """
        Review generated content.

        Args:
            content:
                Response generated by another agent.

        Returns:
            Safety decision.
        """

        logger.info("SafetyAgent reviewing response")

        return super().run(
            user_input=content,
        )
